#!/usr/bin/env bash
# solve task

file_path=$1
ip=$2
user=$3
pk=$4

if [ $# -lt 4 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi
scp "$file_path" "$user"@"$ip":~/ -i "$pk"
