#!/usr/bin/env bash
# solve task
sudo su

apt-get install nginx -y

ufw allow 'Nginx HTTP'

service nginx start

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
