#!/usr/bin/env bash
# solve tas
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
bind *:80
mode http
default_backend app
backend app
balance roundrobin
server 509802-web-01 34.237.91.38 check
server 509802-web-02 	52.201.190.28 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
